# Generated by Django 4.2.11 on 2024-04-20 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Loyality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_points', models.IntegerField()),
                ('amount_per_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parking_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decription', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=30)),
                ('document_type', models.CharField(max_length=30)),
                ('document', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('spaces', models.IntegerField()),
                ('statuts', models.BooleanField(blank=True, default=True)),
                ('address', models.CharField(max_length=30)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.city')),
                ('loyalty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.loyality')),
                ('parking_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.parking_type')),
            ],
        ),
    ]
