# Generated by Django 4.2.11 on 2024-04-24 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Loyality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_points', models.IntegerField()),
                ('amount_per_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parking_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decription', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=30)),
                ('document_type', models.CharField(max_length=30)),
                ('document', models.CharField(default=None, max_length=30)),
                ('name_credit_card', models.CharField(default=None, max_length=30)),
                ('credit_number_card', models.IntegerField(default=None)),
                ('token', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=30)),
                ('vehicle_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('spaces', models.IntegerField()),
                ('current_capacity', models.IntegerField(default=0)),
                ('statuts', models.BooleanField(blank=True, default=True)),
                ('address', models.CharField(max_length=30)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.city')),
                ('loyalty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.loyality')),
                ('parking_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.parking_type')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.fee')),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='Parking_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.parkinglot')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.feetype'),
        ),
        migrations.AddField(
            model_name='fee',
            name='vehicle_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.vehicletype'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.parkinglot')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('vehicle_entry', models.DateTimeField()),
                ('vehicle_exit', models.DateTimeField()),
                ('total_time', models.TimeField()),
                ('points_used', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.booking')),
                ('payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.paymentmethod')),
            ],
        ),
    ]
