# Generated by Django 4.2.11 on 2024-04-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='example',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
