# Generated by Django 4.2.11 on 2024-04-20 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.parkinglot')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.schedule')),
            ],
        ),
    ]
