# Generated by Django 4.2.11 on 2024-04-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_parkinglot_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='example',
        ),
    ]
