# Generated by Django 4.2.11 on 2024-04-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_bills_parking_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.vehicletype'),
        ),
    ]
