# Generated by Django 4.2.11 on 2024-04-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_parkinglot_example'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loyality',
            new_name='Loyalty',
        ),
    ]
