# Generated by Django 4.2.11 on 2024-04-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_feetype_fee_booking_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.fee')),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.parkinglot')),
            ],
        ),
    ]
