# Generated by Django 4.2.11 on 2024-04-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_loyality_loyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='explanation',
            field=models.CharField(default='prueba', max_length=30),
        ),
    ]
