# Generated by Django 4.2.11 on 2024-04-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_booking_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='explanation',
        ),
    ]
