from API.views.billView import BillViewSet
from API.views.bookingView import BookingViewSet
from API.views.cityView import CityViewSet
from API.views.creditCardView import CreditCardViewSet
from API.views.feeTypeView import FeeTypeViewSet
from API.views.feeView import FeeViewSet
from API.views.loyaltyView import LoyaltyViewSet
from API.views.parkingFeeView import ParkingFeeViewSet
from API.views.parkingScheduleView import ParkingScheduleViewSet
from API.views.parkingTypeView import ParkingTypeViewSet
from API.views.parkingView import ParkingViewSet
from API.views.paymentMethodView import PaymentMethodViewSet
from API.views.pointsView import PointsViewSet
from API.views.roleView import RoleViewSet
from API.views.scheduleView import ScheduleViewSet
from API.views.userRoleView import UserRoleViewSet
from API.views.userView import UserViewSet
from API.views.vehicleTypeView import VehicleTypeViewSet
from API.views.vehicleView import VehicleViewSet
